
# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 4  # number of cpus each job need
memory_per_job: 200  # memory requirement each job need
gpu_type: "v100"

# data
dataset: imagenet1k
data_transforms: imagenet1k_basic
data_loader: imagenet1k_basic
dataset_dir: /data/imagenet
#dataset_dir: /mnt/cephfs_new_wj/uslabcv/meijieru/data/imagenet_lmdb
data_loader_workers: 32 #10

# info
num_classes: 1000
image_size: 224
topk: [1, 5]
num_epochs: 55

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.00004
nesterov: True

# lr
lr: 0.01
lr_scheduler: cos_annealing_iter
#lr_scheduler: butterworth_iter #mixed_iter #gaussian_iter #exp_decaying_iter #cos_annealing_iter
#exp_decaying_gamma: 0.98

# model profiling
profiling: [gpu]
#model_profiling_verbose: True

# pretrain, resume, test_only
pretrained_dir: ''
pretrained_file: ''
resume: ''
test_only: False

#
random_seed: 1
batch_size: 128
model: ''
reset_parameters: True

#
distributed: True
distributed_all_reduce: True
use_diff_seed: True

#
width_divisor: 8
min_width: 1

#
unbiased: False
#rescale: True #False
switchbn: False
clamp: True
normalize: True
bn_calib: False
rescale_type: constant #[stddev, constant]
calib_pact: True

#
kappa: 1.0
bits_list: [8, 7, 6, 5, 4, 3, 2]
weight_quant_scheme: original
act_quant_scheme: original
init_bit: 4.5
target_bitops: 5.35
hard_assign_epoch: 35
# =========================== Override Settings ===========================
fp_pretrained_file: /home/lkj004124/logs/mobilenet_v2-b0353104.pth
log_dir: /home/lkj004124/logs/frac_bits_new/imagenet/0505_result_interp_mbv2_bitops5.35_ws2_v1_sm_tau0.5
model: models.q_mobilenet_v2
double_side: True
data_transforms: imagenet1k_mobile
amp: True
#
window_size: 2
simple_interpolation: True
distance_v1: True
L_value: softmax
tau: 0.5
#
log_interval: 50
log_bitwidth: False
